version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  lint:
    executor: node/default
    steps:
      - checkout
      # this step installs the node packages using cache. for more details - https://circleci.com/developer/orbs/orb/circleci/node#commands-install-packages
      - node/install-packages:
          pkg-manager: npm
          cache-version: v1
          include-branch-in-cache-key: true
      - run:
          command: npm run lint
          name: Run linter
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          cache-version: v1
          include-branch-in-cache-key: true
      - run:
          command: npm run test
          name: Run tests
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          cache-version: v1
          include-branch-in-cache-key: true
      - run:
          command: npm run build
          name: Build app

workflows:
  lint-test-build:
    jobs:
      - lint
      - test
      - build