version: 2.1

orbs:
  nx: nrwl/nx@1.4.0
  codecov: codecov/codecov@3.2.3

aliases:
  - &restore-cache
    restore_cache:
      key: dependencies-cache-{{ checksum "package-lock.json" }}
  - &save-cache
    save_cache:
      key: dependencies-cache-{{ checksum "package-lock.json" }}
      paths:
        - ./node_modules
  - &install-deps
    run:
      name: Install dependencies
      command: npm ci
  - &run-linter
    run:
      name: Lint
      # command: npm run lint
      command: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=lint --parallel=3
  - &build
    run:
      name: Build
      # command: npm run build:only
      command: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=build --parallel=3
  - &run-unit-tests
    run:
      name: Unit-test
      # command: npm run test
      command: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=test --parallel=3 --ci --code-coverage
      
jobs:
  # lint:
  #   docker:
  #     - image: cimg/node:lts
  #   steps:
  #     - checkout
  #     - *restore-cache
  #     - *install-deps
  #     - *save-cache
  #     - *run-linter
  unit-test:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - *run-unit-tests
      - codecov/upload:
          file: coverage/packages/m2ts/lcov.info
          flags: eslint-plugin-migrate-to-typescript
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - *build

workflows:
  lint-test-build:
    jobs:
      # - lint
      - build
          # requires:
          #   - lint
      - unit-test
          # requires:
          #   - lint