version: 2.1

aliases:
  - &restore-cache
    restore_cache:
      key: dependencies-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
  - &save-cache
    save_cache:
      key: dependencies-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      paths:
        - ./node_modules
  - &install-deps
    run:
      name: Install dependencies
      command: npm ci
  - &run-linter
    run:
      name: Lint
      command: npm tun lint
  - &build
    run:
      name: Build
      command: npm run build
  - &run-unit-tests
    run:
      name: Test
      command: npm run test

jobs:
  lint:
    executor: node/default
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - *save-cache
      - *run-linter
  test:
    executor: node/default
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - *save-cache
      - *run-unit-tests
  build:
    executor: node/default
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - *save-cache
      - *build

workflows:
  lint-test-build:
    jobs:
      - lint
      - test
      - build