name: reviewdog
on: pull_request

jobs:
  eslint:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: npm ci

      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          level: warning
          fail_on_error: false