name: Upload coverage to codecov
on: push
  # push:
    # branches:
      # - main
env:
  NX_BASE: origin/main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: nrwl/nx-set-shas@v2
      - run: npm ci
      - run: nx run-many --target=test --all --skip-nx-cache
      - uses: codecov/codecov-action@v3
      # - uses: actions/checkout@main
        # with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          # fetch-depth: 0
      # - run: npx nx affected --base=$NX_BASE --head=$NX_HEAD --target=test --parallel=3 --ci --code-coverage --skip-nx-cache
